---
- hosts: host1
  remote_user: root
  vars_files: 
  - "../vars/vars.yml"
  tasks:
    - name: Check if java installed
      shell: java -version
      register: java_result
    - name: Check if git installed
      shell: git --version
      register: git_result
    - name: Check if config file created 
      stat: path={{ config_file }}
      register: config_file_created
    - name: Check if init file created 
      stat: path=/etc/init.d/jenkins-slave
      register: init_file_created
    - name: Check if jenkins_workdir  created 
      stat: path={{ jenkins_workdir }}
      register: jenkins_workdir_created
    - name: Check if user present
      shell: grep jenkins /etc/passwd
      register: jenkins_user_passwd
    - name: Check if service started
      shell: service jenkins status
      register: service_status

    - assert:
       that:
         - "'java version' in java_result.stderr"
         - "'git version' in git_result.stdout"
         - config_file_created.stat.exists
         - init_file_created.stat.exists
         - jenkins_workdir_created.stat.exists
         - "'jenkins:x' in jenkins_user_passwd.stdout"
         - "'Active: active' in service_status.stdout"