---
- hosts: host1
  remote_user: vagrant
  vars:
    - config_file: "/etc/sysconfig/jenkins-slave"
    - jenkins_workdir: "/opt/jenkins/slave_home"
    - jenkins_user: "jenkins"
    - jenkins_url: "http://10.0.0.1:8080"
    - jenkins_nodename: "10.0.0.15"
    - jenkins_secret: "affb104db1acf8186e24a232396eb778adaff063fe14f2b1b527f3f1653a8050"
  tasks:
  - name: Installing OpenJDK
    yum: name=java-openjdk state=present
    sudo: yes

  - name: Installing git
    yum: name=git state=present
    sudo: yes
    tags:
    - git_install

  - name: Create jenkins user
    user: name=jenkins comment="Jenkins slave user" home=/opt/jenkins shell=/bin/bash
    sudo: yes
    ignore_errors: yes
    tags:
     - user
  - name: Create jenkins config file
    template: src=../src/jenkins-slave dest={{ config_file }} mode=0644
    sudo: yes

  - name: Copy Initfile
    copy: src=../src/jenkins-slave.init dest=/etc/init.d/jenkins-slave mode=0755
    sudo: yes

  - name: Register init file
    shell: chkconfig jenkins-slave on
    sudo: yes

  - name: Create jenkins workdir
    file: path={{ jenkins_workdir }} state=directory owner=jenkins group=jenkins
    sudo: yes

  - name: Start service jenkins-slave
    service: name=jenkins-slave state=started
    sudo: yes
