---
- hosts: host1
  remote_user: root
  vars_files: 
  - "../vars/vars.yml"
  tasks:
  tasks:
  - include: ../tasks/openjdk.yml
  - include: ../tasks/git.yml
  
  - name: Create jenkins user
    user: name=jenkins comment="Jenkins slave user" home=/opt/jenkins shell=/bin/bash
    sudo: yes
    ignore_errors: yes
    tags:
     - user
  - name: Create jenkins config file
    template: src=../src/jenkins-slave dest={{ config_file }} mode=644
    sudo: yes    

  - name: Copy Initfile
    copy: src=../src/jenkins-slave.init dest=/etc/init.d/jenkins-slave mode=755
    sudo: yes

  - name: Register init file
    shell: chkconfig jenkins-slave on
    sudo: yes
    
  - name: Create jenkins workdir
    file: path={{ jenkins_workdir }} state=directory owner=jenkins group=jenkins
    sudo: yes

  - name: Start service jenkins-slave
    service: name=jenkins-slave state=started
    sudo: yes
